{{ if .Values.csiSecrets.enabled }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
    name: {{ .Release.Name }}-csi-secrets
spec:
    provider: {{ .Values.csiSecrets.provider }}
    parameters:
        objects: |
            {{- with .Values.csiSecrets.objects }}
            {{- range $internalName, $details := . }}
            - objectName: "{{ $details.arn }}"
              objectType: "{{ $details.type }}"
              objectalias: {{ $internalName }}
              {{- with .jmesPath }}
              jmesPath:
                  {{- range $key, $object := . }}
                  - path: "{{ $object.path }}"
                    objectAlias: "{{ $object.name }}"
                  {{- end }}
              {{- end }}
            {{- end }}
            {{- end }}
{{ end }}
